"""ProjectVersion storage path nullable

Revision ID: 69245f7782ad
Revises: 1902963db06f
Create Date: 2025-09-09 19:59:50.468899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69245f7782ad"
down_revision: Union[str, Sequence[str], None] = "1902963db06f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so recreate the table
    with op.batch_alter_table("project_versions", recreate="always") as batch_op:
        batch_op.alter_column("storage_path", existing_type=sa.Text(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_versions", recreate="always") as batch_op:
        batch_op.alter_column("storage_path", existing_type=sa.Text(), nullable=False)
    # ### end Alembic commands ###
