"""Added slugs for project name and version string

Revision ID: 74896cfbddf5
Revises: 69245f7782ad
Create Date: 2025-09-13 01:59:17.691278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74896cfbddf5"
down_revision: Union[str, Sequence[str], None] = "69245f7782ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version_slug", sa.String(length=255), nullable=False)
        )

    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("name_slug", sa.String(length=255), nullable=False)
        )
        batch_op.create_unique_constraint("uq_project_name", ["name"])
        batch_op.create_unique_constraint("uq_project_name_slug", ["name_slug"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_constraint("uq_project_name", type_="unique")
        batch_op.drop_constraint("uq_project_name_slug", type_="unique")
        batch_op.drop_column("name_slug")

    with op.batch_alter_table("project_versions", schema=None) as batch_op:
        batch_op.drop_column("version_slug")

    # ### end Alembic commands ###
