"""Initial schema

Revision ID: 7cb784a5631f
Revises:
Create Date: 2025-09-06 00:20:57.791684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import doxydochub.database.database_schema


# revision identifiers, used by Alembic.
revision: str = "7cb784a5631f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column(
            "id", doxydochub.database.database_schema.GUID(length=36), nullable=False
        ),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("origin_url", sa.Text(), nullable=False),
        sa.Column(
            "parent_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_metadata",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=False,
        ),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_versions")
    op.drop_table("project_metadata")
    op.drop_table("projects")
    # ### end Alembic commands ###
