"""Initial db schema

Revision ID: f34a1703c846
Revises:
Create Date: 2025-09-14 22:24:25.583227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import doxydochub.database.database_schema

# revision identifiers, used by Alembic.
revision: str = "f34a1703c846"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_projects",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("name_slug", sa.String(length=255), nullable=False),
        sa.Column("origin_url", sa.Text(), nullable=False),
        sa.Column(
            "latest_version_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=True,
        ),
        sa.Column(
            "parent_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "id", doxydochub.database.database_schema.GUID(length=36), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["latest_version_id"],
            ["doc_versions.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["doc_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name_slug"),
    )
    op.create_table(
        "doc_versions",
        sa.Column(
            "id", doxydochub.database.database_schema.GUID(length=36), nullable=False
        ),
        sa.Column("version", sa.String(length=255), nullable=False),
        sa.Column("version_slug", sa.String(length=255), nullable=False),
        sa.Column(
            "project_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=False,
        ),
        sa.Column("storage_path", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["doc_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "objects_metadata",
        sa.Column(
            "parent_id",
            doxydochub.database.database_schema.GUID(length=36),
            nullable=False,
        ),
        sa.Column("parent_type", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "id", doxydochub.database.database_schema.GUID(length=36), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("objects_metadata")
    op.drop_table("doc_versions")
    op.drop_table("doc_projects")
    # ### end Alembic commands ###
